main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
# DO NOT put real secrets here. Use .dev.vars for local and 'wrangler secret put' for prod.
MAPBOX_ACCESS_TOKEN = "pk.your_token_here"
LOG_LEVEL = "info"

[[ratelimits]]
name = "RL_DEFAULT"
namespace_id = "1001"
[ratelimits.simple]
limit = 30
period = 60

[[ratelimits]]
name = "RL_DRIVER"
namespace_id = "1001"
[ratelimits.simple]
limit = 60
period = 60

[env.staging]
name = "staging"

[env.dev]
name = "dev"
